In [7]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/iris.csv/other/default/1/Iris.csv

In [8]:
import pandas as pd

# Load the Iris dataset
iris=pd.read_csv('/kaggle/input/iris.csv/other/default/1/Iris.csv')

# Check for missing values in the dataset
missing_data=iris.isnull().sum()
missing_data

Id               0
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

In [13]:
# List of numerical columns
numerical_columns=['SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm']

# Fill missing values in numerical columns with the median
for col in numerical_columns:
    iris[col] = iris[col].fillna(iris[col].median())  # Assign the filled column back to the DataFrame

In [14]:
# Check and handle missing values in the 'Species' column
if iris['Species'].isnull().sum() > 0:
    iris['Species'] = iris['Species'].fillna(iris['Species'].mode()[0])  # Use the mode and assign it back

In [15]:
#step2_1
# Remove duplicate rows in the dataset
iris.drop_duplicates(inplace=True)

# Verify the result by checking the number of rows before and after removing duplicates
print(f"Number of rows after removing duplicates: {iris.shape[0]}")

Number of rows after removing duplicates: 150

In [16]:
#step2_2
# Create separate columns for sepal_area and petal_area
iris['sepal_area'] = iris['SepalLengthCm'] * iris['SepalWidthCm']
iris['petal_area'] = iris['PetalLengthCm'] * iris['PetalWidthCm']

# Create the total_area column by adding the sepal_area and petal_area
iris['total_area'] = iris['sepal_area'] + iris['petal_area']

# Display the updated dataset to check the new columns
print(iris[['SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm', 'sepal_area', 'petal_area', 'total_area']].head())

   SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  sepal_area  \
0            5.1           3.5            1.4           0.2       17.85
1            4.9           3.0            1.4           0.2       14.70
2            4.7           3.2            1.3           0.2       15.04
3            4.6           3.1            1.5           0.2       14.26
4            5.0           3.6            1.4           0.2       18.00

   petal_area  total_area
0        0.28       18.13
1        0.28       14.98
2        0.26       15.30
3        0.30       14.56
4        0.28       18.28

In [17]:
#step2_3
# Drop rows that still have missing values after imputation
iris.dropna(inplace=True)

# Verify that there are no more missing values
missing_data_after_dropping = iris.isnull().sum()
print(missing_data_after_dropping)

Id               0
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
sepal_area       0
petal_area       0
total_area       0
dtype: int64

In [18]:
#step3_1
# Map species to numerical values
species_mapping = {'setosa': 0, 'versicolor': 1, 'virginica': 2}
iris['Species'] = iris['Species'].map(species_mapping)

# Verify the conversion
print(iris[['Species']].head())

   Species
0      NaN
1      NaN
2      NaN
3      NaN
4      NaN

In [19]:
#step3_2
# Group the data by the transformed 'Species' column and calculate the sum of the numeric columns
aggregation_result = iris.groupby('Species')[['SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm']].sum()

# Display the aggregation result
print(aggregation_result)

Empty DataFrame
Columns: [SepalLengthCm, SepalWidthCm, PetalLengthCm, PetalWidthCm]
Index: []

In [20]:
#step4
# Reshape the dataset into a long format using the melt() function
iris_long = iris.melt(id_vars=['Species'], 
                     value_vars=['SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm'],
                     var_name='Attribute', 
                     value_name='Value')

# Display the reshaped dataset
print(iris_long.head())

   Species      Attribute  Value
0      NaN  SepalLengthCm    5.1
1      NaN  SepalLengthCm    4.9
2      NaN  SepalLengthCm    4.7
3      NaN  SepalLengthCm    4.6
4      NaN  SepalLengthCm    5.0